import React, { useState, useEffect, useRef, useCallback } from 'react';
import {
  Compass,
  ArrowRight,
  ArrowLeft,
  X,
  Check,
  Layers,
  Sliders,
  Radio,
  Volume2,
  FileSpreadsheet,
  Eye,
  Sparkles,
  Info,
  Lightbulb,
} from 'lucide-react';

export interface TourStep {
  id: string;
  targetSelector: string;
  category: string;
  title: string;
  icon: React.ComponentType<{ className?: string }>;
  description: string;
  proTip?: string;
  preferredPlacement?: 'top' | 'bottom' | 'auto';
}

export const TOUR_STEPS: TourStep[] = [
  {
    id: 'header-presets',
    targetSelector: '#header-presets',
    category: 'Operational Templates',
    title: 'Header Presets & Tasks',
    icon: Layers,
    description:
      'Quick-launch battle-tested remote sensing workflows with a single click. Switch between Flood Inundation, Multi-Class Land Cover, Deforestation Change Detection, Agricultural Stress, and Optical–SAR Radar Fusion.',
    proTip: 'Selecting a preset preconfigures sample scenes, indices, and recommended natural language queries automatically.',
    preferredPlacement: 'bottom',
  },
  {
    id: 'image-panels',
    targetSelector: '#image-panels-container',
    category: 'Satellite Imagery',
    title: 'Dual-Scene Image Panels',
    icon: Eye,
    description:
      'Inspect and supply multispectral Sentinel-2 MSI optical tiles (T1 base) and optional post-event temporal tiles (T2) or Sentinel-1 SAR microwave radar tiles. Choose from built-in demo regions or drag-and-drop custom GeoTIFF/PNG satellite scenes.',
    proTip: 'Drag and drop any satellite raster directly onto either scene card to analyze custom imagery instantly.',
    preferredPlacement: 'bottom',
  },
  {
    id: 'controls',
    targetSelector: '#controls-container',
    category: 'Autonomous Agent',
    title: 'Query & Operational Controls',
    icon: Sliders,
    description:
      'Select operational templates, specify your question in plain natural language, or use the speech transcription microphone to speak naturally. Toggle Google Search or Google Maps grounding to enrich satellite detections with real-world geographic context.',
    proTip: 'Keyboard shortcut: Press ⌘+Enter (or Ctrl+Enter) from inside the query box to execute analysis instantly.',
    preferredPlacement: 'bottom',
  },
  {
    id: 'live-voice-call',
    targetSelector: '#live-voice-conversation-card',
    category: 'Gemini 3.8 Live API',
    title: 'Real-Time Voice Call',
    icon: Radio,
    description:
      'Engage in low-latency bidirectional voice dialogue with Gemini 3.8 Live over WebSockets. Discuss satellite findings, request area estimates, adjust spectral parameters, and dock the call into a mini floating widget while browsing.',
    proTip: 'Press Spacebar to quickly mute or unmute your microphone, and use the Mini Dock button to keep chatting while exploring results.',
    preferredPlacement: 'bottom',
  },
  {
    id: 'visual-evidence',
    targetSelector: '#visual-evidence-container',
    category: 'Computer Vision & Spectral Indices',
    title: 'Visual Evidence & Pixel Inspector',
    icon: Sparkles,
    description:
      'Examine pixel-level segmentation masks and detection bounding boxes. Switch between before/after Swipe Curtain comparison, Opacity blending, and spectral index layers (NDVI vegetation health, NDWI water extent, NDBI urban index). Hover anywhere on the canvas to inspect precise pixel coordinates and land-cover class in real time.',
    proTip: 'Hover your cursor over any point to see the live (X, Y) pixel HUD, or click the fullscreen button for high-resolution inspection.',
    preferredPlacement: 'top',
  },
  {
    id: 'audio-explanation',
    targetSelector: '#audio-explanation-card',
    category: 'Multilingual Audio Briefing',
    title: 'Spoken Audio Briefing',
    icon: Volume2,
    description:
      'Listen to synthesized spoken explanations of satellite findings generated by Gemini in your chosen language (English, Spanish, French, German, Hindi, Japanese, and more) and preferred style: simple and jargon-free for general audiences or technical with scientific indices.',
    proTip: 'Generated audio is cached client-side for zero-latency replay, and includes 5s skip buttons and WAV export.',
    preferredPlacement: 'top',
  },
  {
    id: 'findings-export',
    targetSelector: '#findings-export-container',
    category: 'Geospatial Delivery',
    title: 'Analytical Findings & Export',
    icon: FileSpreadsheet,
    description:
      'Review executive synthesis reports, bi-temporal land-cover deltas, hectare statistics, and spectral shift indices. One-click export your data into standard GIS GeoJSON features, CSV statistical tables, copyable summaries, or bundled ZIP archives.',
    proTip: 'Use the ZIP export to download all masks, GeoJSON, CSV metrics, and metadata in one complete bundle ready for QGIS or ArcGIS.',
    preferredPlacement: 'top',
  },
];

interface AppTourProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectPreset?: (presetName: string) => void;
}

export const AppTour: React.FC<AppTourProps> = ({ isOpen, onClose }) => {
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [targetRect, setTargetRect] = useState<DOMRect | null>(null);
  const [placement, setPlacement] = useState<'top' | 'bottom'>('bottom');
  const [tooltipPos, setTooltipPos] = useState<{ top: number; left: number }>({ top: 0, left: 0 });
  const [arrowPos, setArrowPos] = useState<{ left: number }>({ left: 50 });
  const tooltipRef = useRef<HTMLDivElement | null>(null);

  const step = TOUR_STEPS[currentStepIndex];

  // Measure and align spotlight to current target element
  const updatePosition = useCallback(() => {
    if (!step) return;
    const element = document.querySelector(step.targetSelector) as HTMLElement | null;
    if (!element) return;

    const rect = element.getBoundingClientRect();
    setTargetRect(rect);

    const tooltipWidth = Math.min(420, window.innerWidth - 32);
    const tooltipHeight = 280; // approximate height
    const padding = 16;

    // Determine vertical placement: top or bottom
    const spaceBelow = window.innerHeight - rect.bottom;
    const spaceAbove = rect.top;

    let chosenPlacement: 'top' | 'bottom' = 'bottom';
    if (step.preferredPlacement === 'top' && spaceAbove > tooltipHeight + padding) {
      chosenPlacement = 'top';
    } else if (step.preferredPlacement === 'bottom' && spaceBelow > tooltipHeight + padding) {
      chosenPlacement = 'bottom';
    } else {
      chosenPlacement = spaceBelow >= spaceAbove ? 'bottom' : 'top';
    }
    setPlacement(chosenPlacement);

    // Calculate ideal tooltip top coordinate
    let top = 0;
    if (chosenPlacement === 'bottom') {
      top = rect.bottom + 14;
    } else {
      top = rect.top - tooltipHeight - 14;
    }

    // Clamp top so tooltip is always visible
    top = Math.max(padding, Math.min(window.innerHeight - tooltipHeight - padding, top));

    // Calculate ideal tooltip left coordinate (centered on target element)
    const targetCenterX = rect.left + rect.width / 2;
    let left = targetCenterX - tooltipWidth / 2;

    // Clamp left within viewport margins
    left = Math.max(padding, Math.min(window.innerWidth - tooltipWidth - padding, left));

    setTooltipPos({ top, left });

    // Position arrow relative to tooltip
    const arrowLeft = Math.max(20, Math.min(tooltipWidth - 20, targetCenterX - left));
    setArrowPos({ left: arrowLeft });
  }, [step]);

  // Scroll element into view and update positions when step changes
  useEffect(() => {
    if (!isOpen || !step) return;

    const element = document.querySelector(step.targetSelector) as HTMLElement | null;
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'center' });

      // Immediate measurement
      updatePosition();

      // Recalculate after smooth scrolling settles
      const t1 = setTimeout(updatePosition, 200);
      const t2 = setTimeout(updatePosition, 500);

      return () => {
        clearTimeout(t1);
        clearTimeout(t2);
      };
    }
  }, [isOpen, currentStepIndex, step, updatePosition]);

  // Recompute position on resize and scroll
  useEffect(() => {
    if (!isOpen) return;

    const handleScrollOrResize = () => {
      updatePosition();
    };

    window.addEventListener('resize', handleScrollOrResize, { passive: true });
    window.addEventListener('scroll', handleScrollOrResize, { passive: true });

    return () => {
      window.removeEventListener('resize', handleScrollOrResize);
      window.removeEventListener('scroll', handleScrollOrResize);
    };
  }, [isOpen, updatePosition]);

  // Keyboard navigation
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        onClose();
      } else if (e.key === 'ArrowRight' || e.key === 'Enter') {
        e.preventDefault();
        handleNext();
      } else if (e.key === 'ArrowLeft') {
        e.preventDefault();
        handlePrev();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, currentStepIndex]);

  // Reset to first step on open
  useEffect(() => {
    if (isOpen) {
      setCurrentStepIndex(0);
    }
  }, [isOpen]);

  if (!isOpen || !step) return null;

  const handleNext = () => {
    if (currentStepIndex < TOUR_STEPS.length - 1) {
      setCurrentStepIndex((prev) => prev + 1);
    } else {
      onClose();
    }
  };

  const handlePrev = () => {
    if (currentStepIndex > 0) {
      setCurrentStepIndex((prev) => prev - 1);
    }
  };

  const IconComponent = step.icon;
  const isLastStep = currentStepIndex === TOUR_STEPS.length - 1;
  const progressPct = ((currentStepIndex + 1) / TOUR_STEPS.length) * 100;

  // Spotlight padding around highlighted element
  const spotPad = 6;

  return (
    <div
      id="guided-tour-overlay"
      className="fixed inset-0 z-50 overflow-hidden select-none pointer-events-auto"
      role="dialog"
      aria-modal="true"
      aria-label="Application Walkthrough Tour"
    >
      {/* Dimmed backdrop with transparent cutout spotlight */}
      {targetRect ? (
        <svg
          className="absolute inset-0 w-full h-full pointer-events-none transition-all duration-300 ease-out"
          style={{ width: '100vw', height: '100vh' }}
        >
          <defs>
            <mask id="tour-spotlight-mask">
              {/* Fill entire screen with solid white */}
              <rect x="0" y="0" width="100%" height="100%" fill="white" />
              {/* Cut out rectangular window over the highlighted element with rounded corners */}
              <rect
                x={Math.max(0, targetRect.left - spotPad)}
                y={Math.max(0, targetRect.top - spotPad)}
                width={Math.max(0, targetRect.width + spotPad * 2)}
                height={Math.max(0, targetRect.height + spotPad * 2)}
                rx="14"
                ry="14"
                fill="black"
              />
            </mask>
          </defs>
          {/* Black backdrop with opacity masked by the cutout */}
          <rect
            x="0"
            y="0"
            width="100%"
            height="100%"
            fill="rgba(2, 6, 23, 0.78)"
            mask="url(#tour-spotlight-mask)"
          />
        </svg>
      ) : (
        <div className="absolute inset-0 bg-slate-950/80 backdrop-blur-xs" />
      )}

      {/* Glowing boundary frame around the targeted element */}
      {targetRect && (
        <div
          className="fixed pointer-events-none rounded-xl border-2 border-emerald-400 ring-4 ring-emerald-500/30 shadow-[0_0_35px_rgba(52,211,153,0.4)] transition-all duration-300 ease-out animate-pulse"
          style={{
            top: targetRect.top - spotPad,
            left: targetRect.left - spotPad,
            width: targetRect.width + spotPad * 2,
            height: targetRect.height + spotPad * 2,
          }}
        />
      )}

      {/* Floating Tour Tooltip Card */}
      <div
        ref={tooltipRef}
        className="fixed z-50 w-[380px] max-w-[calc(100vw-32px)] sm:w-[430px] rounded-2xl bg-slate-900/98 backdrop-blur-xl border border-slate-700/90 shadow-2xl shadow-black/80 text-slate-100 p-5 transition-all duration-200 ease-out"
        style={{
          top: tooltipPos.top,
          left: tooltipPos.left,
        }}
      >
        {/* Animated Directional Pointer Arrow */}
        <div
          className={`absolute w-4 h-4 bg-slate-900 border-slate-700/90 transform rotate-45 pointer-events-none ${
            placement === 'bottom'
              ? '-top-2 border-t border-l animate-bounce'
              : '-bottom-2 border-b border-r animate-bounce'
          }`}
          style={{
            left: arrowPos.left - 8,
          }}
        />

        {/* Top Header: Step Badge, Category & Skip button */}
        <div className="flex items-center justify-between gap-3 mb-3 border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold tracking-wide bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
              Step {currentStepIndex + 1} of {TOUR_STEPS.length}
            </span>
            <span className="text-[11px] font-medium text-slate-400 uppercase tracking-wider truncate max-w-[170px]">
              {step.category}
            </span>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-100 hover:bg-slate-800 transition cursor-pointer"
            title="Skip Tour (Esc)"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Title and Icon */}
        <div className="flex items-start gap-3 mb-2.5">
          <div className="p-2.5 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 shrink-0 mt-0.5 shadow-sm">
            <IconComponent className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white tracking-tight leading-snug">
              {step.title}
            </h3>
            <p className="text-xs text-slate-300 mt-1 leading-relaxed">
              {step.description}
            </p>
          </div>
        </div>

        {/* Pro Tip Callout */}
        {step.proTip && (
          <div className="mb-4 flex items-start gap-2 bg-emerald-950/30 border border-emerald-500/20 rounded-xl p-2.5 text-[11px] text-emerald-200/90 leading-normal">
            <Lightbulb className="w-3.5 h-3.5 text-emerald-400 shrink-0 mt-0.5" />
            <div>
              <strong className="text-emerald-300 font-semibold">Pro Tip: </strong>
              {step.proTip}
            </div>
          </div>
        )}

        {/* Step Progress Line */}
        <div className="w-full bg-slate-800 h-1 rounded-full overflow-hidden mb-4">
          <div
            className="h-full bg-gradient-to-r from-emerald-400 to-teal-400 transition-all duration-300"
            style={{ width: `${progressPct}%` }}
          />
        </div>

        {/* Footer Navigation Controls */}
        <div className="flex items-center justify-between gap-2">
          {/* Quick Step Indicator Dots */}
          <div className="flex items-center gap-1.5">
            {TOUR_STEPS.map((s, idx) => (
              <button
                key={s.id}
                type="button"
                onClick={() => setCurrentStepIndex(idx)}
                className={`w-2 h-2 rounded-full transition-all cursor-pointer ${
                  idx === currentStepIndex
                    ? 'w-5 bg-emerald-400'
                    : idx < currentStepIndex
                    ? 'bg-emerald-700'
                    : 'bg-slate-700 hover:bg-slate-600'
                }`}
                title={`Jump to ${s.title}`}
              />
            ))}
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrev}
              disabled={currentStepIndex === 0}
              className={`flex items-center gap-1 px-3 py-1.5 rounded-xl text-xs font-medium border transition cursor-pointer ${
                currentStepIndex === 0
                  ? 'opacity-40 cursor-not-allowed border-slate-800 text-slate-600'
                  : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border-slate-700'
              }`}
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span>Previous</span>
            </button>

            <button
              type="button"
              onClick={handleNext}
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-xl text-xs font-semibold bg-emerald-500 hover:bg-emerald-400 text-slate-950 shadow-md shadow-emerald-500/20 transition cursor-pointer active:scale-95"
            >
              <span>{isLastStep ? 'Finish Tour' : 'Next'}</span>
              {isLastStep ? (
                <Check className="w-3.5 h-3.5 stroke-[2.5]" />
              ) : (
                <ArrowRight className="w-3.5 h-3.5 stroke-[2.5]" />
              )}
            </button>
          </div>
        </div>

        {/* Keyboard shortcut legend */}
        <div className="mt-3 pt-2 border-t border-slate-800/80 flex items-center justify-between text-[10px] text-slate-500 font-mono">
          <span>← / → Navigate</span>
          <span>Esc to Skip</span>
        </div>
      </div>
    </div>
  );
};
